name: FCIChat
version: 1.3
author: Filip Zocktan & HappyHappyBoy
main: de.teamfci.fcichat.FortressCombat
commands:
  combatcast:
    description: Sendet eine Combat-Cast-Nachricht
  cc:
    description: Sendet eine Combat-Cast-Nachricht
  fcic:
    description: Zeigt Plugininfo an.
  fcichat:
    description: Zeigt Plugininfo an.
  fortresscombat1chat:
    description: Zeigt Plugininfo an.